[project]
name = "day08-2a202601981-phamducthien"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.3.0",
    "fpdf2>=2.7.0",
    "markitdown[pdf]>=0.1.0",
    "numpy>=1.24.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
]
